// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jogos.proto

// Protobuf Java Version: 3.25.1
package cadastrojogo.javafx.mensageiro;

public final class Jogos {
  private Jogos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DadosJogoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cadastrojogo.javafx.mensageiro.DadosJogoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string time_fora = 1;</code>
     * @return The timeFora.
     */
    java.lang.String getTimeFora();
    /**
     * <code>string time_fora = 1;</code>
     * @return The bytes for timeFora.
     */
    com.google.protobuf.ByteString
        getTimeForaBytes();

    /**
     * <code>string time_casa = 2;</code>
     * @return The timeCasa.
     */
    java.lang.String getTimeCasa();
    /**
     * <code>string time_casa = 2;</code>
     * @return The bytes for timeCasa.
     */
    com.google.protobuf.ByteString
        getTimeCasaBytes();

    /**
     * <code>string gols_fora = 3;</code>
     * @return The golsFora.
     */
    java.lang.String getGolsFora();
    /**
     * <code>string gols_fora = 3;</code>
     * @return The bytes for golsFora.
     */
    com.google.protobuf.ByteString
        getGolsForaBytes();

    /**
     * <code>string gols_casa = 4;</code>
     * @return The golsCasa.
     */
    java.lang.String getGolsCasa();
    /**
     * <code>string gols_casa = 4;</code>
     * @return The bytes for golsCasa.
     */
    com.google.protobuf.ByteString
        getGolsCasaBytes();

    /**
     * <code>string arbitro = 5;</code>
     * @return The arbitro.
     */
    java.lang.String getArbitro();
    /**
     * <code>string arbitro = 5;</code>
     * @return The bytes for arbitro.
     */
    com.google.protobuf.ByteString
        getArbitroBytes();
  }
  /**
   * Protobuf type {@code cadastrojogo.javafx.mensageiro.DadosJogoRequest}
   */
  public static final class DadosJogoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cadastrojogo.javafx.mensageiro.DadosJogoRequest)
      DadosJogoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DadosJogoRequest.newBuilder() to construct.
    private DadosJogoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DadosJogoRequest() {
      timeFora_ = "";
      timeCasa_ = "";
      golsFora_ = "";
      golsCasa_ = "";
      arbitro_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DadosJogoRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.class, cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.Builder.class);
    }

    public static final int TIME_FORA_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timeFora_ = "";
    /**
     * <code>string time_fora = 1;</code>
     * @return The timeFora.
     */
    @java.lang.Override
    public java.lang.String getTimeFora() {
      java.lang.Object ref = timeFora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeFora_ = s;
        return s;
      }
    }
    /**
     * <code>string time_fora = 1;</code>
     * @return The bytes for timeFora.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeForaBytes() {
      java.lang.Object ref = timeFora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeFora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_CASA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timeCasa_ = "";
    /**
     * <code>string time_casa = 2;</code>
     * @return The timeCasa.
     */
    @java.lang.Override
    public java.lang.String getTimeCasa() {
      java.lang.Object ref = timeCasa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeCasa_ = s;
        return s;
      }
    }
    /**
     * <code>string time_casa = 2;</code>
     * @return The bytes for timeCasa.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeCasaBytes() {
      java.lang.Object ref = timeCasa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeCasa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOLS_FORA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object golsFora_ = "";
    /**
     * <code>string gols_fora = 3;</code>
     * @return The golsFora.
     */
    @java.lang.Override
    public java.lang.String getGolsFora() {
      java.lang.Object ref = golsFora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        golsFora_ = s;
        return s;
      }
    }
    /**
     * <code>string gols_fora = 3;</code>
     * @return The bytes for golsFora.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGolsForaBytes() {
      java.lang.Object ref = golsFora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        golsFora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOLS_CASA_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object golsCasa_ = "";
    /**
     * <code>string gols_casa = 4;</code>
     * @return The golsCasa.
     */
    @java.lang.Override
    public java.lang.String getGolsCasa() {
      java.lang.Object ref = golsCasa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        golsCasa_ = s;
        return s;
      }
    }
    /**
     * <code>string gols_casa = 4;</code>
     * @return The bytes for golsCasa.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGolsCasaBytes() {
      java.lang.Object ref = golsCasa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        golsCasa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARBITRO_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object arbitro_ = "";
    /**
     * <code>string arbitro = 5;</code>
     * @return The arbitro.
     */
    @java.lang.Override
    public java.lang.String getArbitro() {
      java.lang.Object ref = arbitro_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arbitro_ = s;
        return s;
      }
    }
    /**
     * <code>string arbitro = 5;</code>
     * @return The bytes for arbitro.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArbitroBytes() {
      java.lang.Object ref = arbitro_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arbitro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeFora_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeFora_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeCasa_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeCasa_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(golsFora_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, golsFora_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(golsCasa_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, golsCasa_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arbitro_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, arbitro_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeFora_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeFora_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeCasa_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeCasa_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(golsFora_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, golsFora_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(golsCasa_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, golsCasa_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(arbitro_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, arbitro_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest)) {
        return super.equals(obj);
      }
      cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest other = (cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest) obj;

      if (!getTimeFora()
          .equals(other.getTimeFora())) return false;
      if (!getTimeCasa()
          .equals(other.getTimeCasa())) return false;
      if (!getGolsFora()
          .equals(other.getGolsFora())) return false;
      if (!getGolsCasa()
          .equals(other.getGolsCasa())) return false;
      if (!getArbitro()
          .equals(other.getArbitro())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FORA_FIELD_NUMBER;
      hash = (53 * hash) + getTimeFora().hashCode();
      hash = (37 * hash) + TIME_CASA_FIELD_NUMBER;
      hash = (53 * hash) + getTimeCasa().hashCode();
      hash = (37 * hash) + GOLS_FORA_FIELD_NUMBER;
      hash = (53 * hash) + getGolsFora().hashCode();
      hash = (37 * hash) + GOLS_CASA_FIELD_NUMBER;
      hash = (53 * hash) + getGolsCasa().hashCode();
      hash = (37 * hash) + ARBITRO_FIELD_NUMBER;
      hash = (53 * hash) + getArbitro().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cadastrojogo.javafx.mensageiro.DadosJogoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cadastrojogo.javafx.mensageiro.DadosJogoRequest)
        cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.class, cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.Builder.class);
      }

      // Construct using cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timeFora_ = "";
        timeCasa_ = "";
        golsFora_ = "";
        golsCasa_ = "";
        arbitro_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_descriptor;
      }

      @java.lang.Override
      public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest getDefaultInstanceForType() {
        return cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest build() {
        cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest buildPartial() {
        cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest result = new cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timeFora_ = timeFora_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timeCasa_ = timeCasa_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.golsFora_ = golsFora_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.golsCasa_ = golsCasa_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.arbitro_ = arbitro_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest) {
          return mergeFrom((cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest other) {
        if (other == cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest.getDefaultInstance()) return this;
        if (!other.getTimeFora().isEmpty()) {
          timeFora_ = other.timeFora_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTimeCasa().isEmpty()) {
          timeCasa_ = other.timeCasa_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getGolsFora().isEmpty()) {
          golsFora_ = other.golsFora_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getGolsCasa().isEmpty()) {
          golsCasa_ = other.golsCasa_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getArbitro().isEmpty()) {
          arbitro_ = other.arbitro_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                timeFora_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                timeCasa_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                golsFora_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                golsCasa_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                arbitro_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object timeFora_ = "";
      /**
       * <code>string time_fora = 1;</code>
       * @return The timeFora.
       */
      public java.lang.String getTimeFora() {
        java.lang.Object ref = timeFora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeFora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time_fora = 1;</code>
       * @return The bytes for timeFora.
       */
      public com.google.protobuf.ByteString
          getTimeForaBytes() {
        java.lang.Object ref = timeFora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeFora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time_fora = 1;</code>
       * @param value The timeFora to set.
       * @return This builder for chaining.
       */
      public Builder setTimeFora(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timeFora_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string time_fora = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeFora() {
        timeFora_ = getDefaultInstance().getTimeFora();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string time_fora = 1;</code>
       * @param value The bytes for timeFora to set.
       * @return This builder for chaining.
       */
      public Builder setTimeForaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timeFora_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object timeCasa_ = "";
      /**
       * <code>string time_casa = 2;</code>
       * @return The timeCasa.
       */
      public java.lang.String getTimeCasa() {
        java.lang.Object ref = timeCasa_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeCasa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time_casa = 2;</code>
       * @return The bytes for timeCasa.
       */
      public com.google.protobuf.ByteString
          getTimeCasaBytes() {
        java.lang.Object ref = timeCasa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeCasa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time_casa = 2;</code>
       * @param value The timeCasa to set.
       * @return This builder for chaining.
       */
      public Builder setTimeCasa(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timeCasa_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string time_casa = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeCasa() {
        timeCasa_ = getDefaultInstance().getTimeCasa();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string time_casa = 2;</code>
       * @param value The bytes for timeCasa to set.
       * @return This builder for chaining.
       */
      public Builder setTimeCasaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timeCasa_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object golsFora_ = "";
      /**
       * <code>string gols_fora = 3;</code>
       * @return The golsFora.
       */
      public java.lang.String getGolsFora() {
        java.lang.Object ref = golsFora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          golsFora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gols_fora = 3;</code>
       * @return The bytes for golsFora.
       */
      public com.google.protobuf.ByteString
          getGolsForaBytes() {
        java.lang.Object ref = golsFora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          golsFora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gols_fora = 3;</code>
       * @param value The golsFora to set.
       * @return This builder for chaining.
       */
      public Builder setGolsFora(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        golsFora_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string gols_fora = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGolsFora() {
        golsFora_ = getDefaultInstance().getGolsFora();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string gols_fora = 3;</code>
       * @param value The bytes for golsFora to set.
       * @return This builder for chaining.
       */
      public Builder setGolsForaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        golsFora_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object golsCasa_ = "";
      /**
       * <code>string gols_casa = 4;</code>
       * @return The golsCasa.
       */
      public java.lang.String getGolsCasa() {
        java.lang.Object ref = golsCasa_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          golsCasa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gols_casa = 4;</code>
       * @return The bytes for golsCasa.
       */
      public com.google.protobuf.ByteString
          getGolsCasaBytes() {
        java.lang.Object ref = golsCasa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          golsCasa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gols_casa = 4;</code>
       * @param value The golsCasa to set.
       * @return This builder for chaining.
       */
      public Builder setGolsCasa(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        golsCasa_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string gols_casa = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGolsCasa() {
        golsCasa_ = getDefaultInstance().getGolsCasa();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string gols_casa = 4;</code>
       * @param value The bytes for golsCasa to set.
       * @return This builder for chaining.
       */
      public Builder setGolsCasaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        golsCasa_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object arbitro_ = "";
      /**
       * <code>string arbitro = 5;</code>
       * @return The arbitro.
       */
      public java.lang.String getArbitro() {
        java.lang.Object ref = arbitro_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          arbitro_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string arbitro = 5;</code>
       * @return The bytes for arbitro.
       */
      public com.google.protobuf.ByteString
          getArbitroBytes() {
        java.lang.Object ref = arbitro_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          arbitro_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string arbitro = 5;</code>
       * @param value The arbitro to set.
       * @return This builder for chaining.
       */
      public Builder setArbitro(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        arbitro_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string arbitro = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearArbitro() {
        arbitro_ = getDefaultInstance().getArbitro();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string arbitro = 5;</code>
       * @param value The bytes for arbitro to set.
       * @return This builder for chaining.
       */
      public Builder setArbitroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        arbitro_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cadastrojogo.javafx.mensageiro.DadosJogoRequest)
    }

    // @@protoc_insertion_point(class_scope:cadastrojogo.javafx.mensageiro.DadosJogoRequest)
    private static final cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest();
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DadosJogoRequest>
        PARSER = new com.google.protobuf.AbstractParser<DadosJogoRequest>() {
      @java.lang.Override
      public DadosJogoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DadosJogoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DadosJogoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DadosJogoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cadastrojogo.javafx.mensageiro.DadosJogoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mensagem = 1;</code>
     * @return The mensagem.
     */
    java.lang.String getMensagem();
    /**
     * <code>string mensagem = 1;</code>
     * @return The bytes for mensagem.
     */
    com.google.protobuf.ByteString
        getMensagemBytes();
  }
  /**
   * Protobuf type {@code cadastrojogo.javafx.mensageiro.DadosJogoResponse}
   */
  public static final class DadosJogoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cadastrojogo.javafx.mensageiro.DadosJogoResponse)
      DadosJogoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DadosJogoResponse.newBuilder() to construct.
    private DadosJogoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DadosJogoResponse() {
      mensagem_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DadosJogoResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.class, cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.Builder.class);
    }

    public static final int MENSAGEM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mensagem_ = "";
    /**
     * <code>string mensagem = 1;</code>
     * @return The mensagem.
     */
    @java.lang.Override
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      }
    }
    /**
     * <code>string mensagem = 1;</code>
     * @return The bytes for mensagem.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mensagem_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mensagem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse)) {
        return super.equals(obj);
      }
      cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse other = (cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse) obj;

      if (!getMensagem()
          .equals(other.getMensagem())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
      hash = (53 * hash) + getMensagem().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cadastrojogo.javafx.mensageiro.DadosJogoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cadastrojogo.javafx.mensageiro.DadosJogoResponse)
        cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.class, cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.Builder.class);
      }

      // Construct using cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mensagem_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cadastrojogo.javafx.mensageiro.Jogos.internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_descriptor;
      }

      @java.lang.Override
      public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse getDefaultInstanceForType() {
        return cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse build() {
        cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse buildPartial() {
        cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse result = new cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mensagem_ = mensagem_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse) {
          return mergeFrom((cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse other) {
        if (other == cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse.getDefaultInstance()) return this;
        if (!other.getMensagem().isEmpty()) {
          mensagem_ = other.mensagem_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mensagem_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object mensagem_ = "";
      /**
       * <code>string mensagem = 1;</code>
       * @return The mensagem.
       */
      public java.lang.String getMensagem() {
        java.lang.Object ref = mensagem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mensagem_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mensagem = 1;</code>
       * @return The bytes for mensagem.
       */
      public com.google.protobuf.ByteString
          getMensagemBytes() {
        java.lang.Object ref = mensagem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mensagem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mensagem = 1;</code>
       * @param value The mensagem to set.
       * @return This builder for chaining.
       */
      public Builder setMensagem(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mensagem_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string mensagem = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMensagem() {
        mensagem_ = getDefaultInstance().getMensagem();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string mensagem = 1;</code>
       * @param value The bytes for mensagem to set.
       * @return This builder for chaining.
       */
      public Builder setMensagemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mensagem_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cadastrojogo.javafx.mensageiro.DadosJogoResponse)
    }

    // @@protoc_insertion_point(class_scope:cadastrojogo.javafx.mensageiro.DadosJogoResponse)
    private static final cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse();
    }

    public static cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DadosJogoResponse>
        PARSER = new com.google.protobuf.AbstractParser<DadosJogoResponse>() {
      @java.lang.Override
      public DadosJogoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DadosJogoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DadosJogoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cadastrojogo.javafx.mensageiro.Jogos.DadosJogoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013jogos.proto\022\036cadastrojogo.javafx.mensa" +
      "geiro\"o\n\020DadosJogoRequest\022\021\n\ttime_fora\030\001" +
      " \001(\t\022\021\n\ttime_casa\030\002 \001(\t\022\021\n\tgols_fora\030\003 \001" +
      "(\t\022\021\n\tgols_casa\030\004 \001(\t\022\017\n\007arbitro\030\005 \001(\t\"%" +
      "\n\021DadosJogoResponse\022\020\n\010mensagem\030\001 \001(\t2\207\001" +
      "\n\014CadastroJogo\022w\n\020InserirDadosJogo\0220.cad" +
      "astrojogo.javafx.mensageiro.DadosJogoReq" +
      "uest\0321.cadastrojogo.javafx.mensageiro.Da" +
      "dosJogoResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadastrojogo_javafx_mensageiro_DadosJogoRequest_descriptor,
        new java.lang.String[] { "TimeFora", "TimeCasa", "GolsFora", "GolsCasa", "Arbitro", });
    internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadastrojogo_javafx_mensageiro_DadosJogoResponse_descriptor,
        new java.lang.String[] { "Mensagem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
